version: "3.8"

services:
  app:
    image: "image_name"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "3000:3000" # your local port should be externalized
    networks:
      - hackincariri 
    healthcheck:
      test: "curl -f http://localhost:3000/health || exit 1" # your application should return 200 on this path 
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
networks:
  hackincariri:
    external: true